/**
 * Benim Bakıcım — SEO configuration
 * Optimized for: bakıcı, yardımcı, ev temizliği, gündelikçi, bebek bakıcısı, yatılı bakıcı, yatılı yardımcı
 * Reference: bakiciburada.com, insanbul.com
 */
const SITE_URL = 'https://benimbakicim.com';
const SITE_NAME = 'Benim Bakıcım';
const DEFAULT_OG_IMAGE = `${SITE_URL}/assets/logo-icon.png`;

const GLOBAL_KEYWORDS = [
  'bakıcı',
  'bakıcı arıyorum',
  'yardımcı',
  'yardımcı arıyorum',
  'ev temizliği',
  'gündelikçi',
  'gündelikçi arıyorum',
  'bebek bakıcısı',
  'bebek bakıcısı arıyorum',
  'yatılı bakıcı',
  'yatılı bakıcı arıyorum',
  'yatılı yardımcı',
  'yatılı yardımcı arıyorum',
  'çocuk bakıcısı',
  'ev yardımcısı',
  'ev yardımcısı arıyorum',
  'günlük temizlik',
  'gündelik temizlik',
  'temizlik personeli',
  'ev işlerine yardımcı',
  'ev işlerine yardımcı kadın arıyorum',
  'yabancı bakıcı',
  'referanslı bakıcı',
  'istanbul bakıcı',
  'istanbul yardımcı',
  'yatılı ev yardımcısı',
  'gündüzlü bakıcı',
  'türkmen bakıcı',
  'özbek bakıcı',
  'filipinli bakıcı',
  'hasta bakıcısı',
  'yaşlı bakıcısı',
].join(', ');

const BUSINESS = {
  name: SITE_NAME,
  url: SITE_URL,
  email: 'info@benimbakicim.com',
  phone: '+905355963545',
  whatsapp: 'https://wa.me/905355963545',
  instagram: 'https://instagram.com/yatili.bakici',
  address: {
    street: 'Soğanlık Yeni Mah. Baltacı Mehmetpaşa Sk. AC Moment Yapı B Blok No: 4 B İç Kapı No: 286',
    locality: 'Kartal/İstanbul',
    region: 'İstanbul',
    postalCode: '34880',
    country: 'TR',
  },
  geo: { lat: 40.9125, lng: 29.1890 },
  hours: 'Mo-Sa 09:00-19:00',
};

/** @type {Record<string, object>} */
const PAGE_SEO = {
  'index.html': {
    path: '/',
    title: 'Bakıcı, Yardımcı, Ev Temizliği | Bebek Bakıcısı, Yatılı Bakıcı, Gündelikçi — İstanbul',
    description:
      'Bakıcı arıyorum diyorsanız Benim Bakıcım — bebek bakıcısı, yatılı bakıcı, yatılı yardımcı, ev yardımcısı, ev temizliği, gündelikçi ve günlük temizlik personeli. Referanslı Türkmen, Özbek bakıcı. İstanbul geneli. WhatsApp: 0535 596 35 45.',
    keywords: GLOBAL_KEYWORDS,
    type: 'website',
    faqs: [
      { q: 'Bakıcı arıyorum, nasıl başvurabilirim?', a: 'Talep formunu doldurun veya WhatsApp\'tan yazın. Danışmanımız 24-48 saat içinde sizi arayarak ihtiyacınızı dinler ve uygun adayları sunar.' },
      { q: 'Yatılı yardımcı ve yatılı bakıcı bulabilir miyim?', a: 'Evet, yatılı bakıcı, yatılı yardımcı ve yatılı ev yardımcısı temini yapıyoruz. 7/24 evde konaklayan referanslı personel sunuyoruz.' },
      { q: 'Gündelikçi ve ev temizliği hizmeti veriyor musunuz?', a: 'Evet, gündelikçi, günlük temizlik personeli, gündelik temizlik ve ev temizliği için referanslı yardımcı temin ediyoruz.' },
      { q: 'Bebek bakıcısı arıyorum, ne kadar sürede bulunur?', a: 'Genellikle birkaç gün içinde referanslı bebek bakıcısı adaylarını yönlendiriyoruz. Acil taleplerde hızlandırılmış eşleştirme yapılır.' },
      { q: 'Yardımcı ve bakıcı adayları güvenilir mi?', a: 'Tüm adaylar yüz yüze mülakat, referans araması, sabıka kaydı sorgusu ve sağlık raporu kontrolünden geçer.' },
      { q: 'Hangi bölgelere hizmet veriyorsunuz?', a: 'İstanbul geneli — tüm ilçelerde hizmet. Yatılı bakıcı taleplerinde Türkiye geneli değerlendirilebilir.' },
    ],
  },
  'pages/bakici-ariyorum.html': {
    path: '/pages/bakici-ariyorum.html',
    title: 'Bakıcı Arıyorum | Referanslı Bakıcı & Yardımcı Bul — İstanbul',
    description: 'Bakıcı arıyorum — bebek bakıcısı, çocuk bakıcısı, yabancı bakıcı, yatılı bakıcı, ev yardımcısı, gündelikçi. Referanslı bakıcı temini. Ücretsiz danışmanlık.',
    keywords: 'bakıcı arıyorum, bakıcı, yardımcı arıyorum, bebek bakıcısı arıyorum, yatılı bakıcı arıyorum, ev yardımcısı arıyorum, istanbul bakıcı arıyorum, referanslı bakıcı',
    service: 'Bakıcı Temini',
    faqs: [
      { q: 'Bakıcı arıyorum, nereden başlamalıyım?', a: 'Talep formunu doldurun veya WhatsApp\'tan yazın. Danışmanımız 24-48 saat içinde sizi arayarak ihtiyacınızı dinler.' },
      { q: 'Bakıcı bulmak ne kadar sürer?', a: 'Genellikle birkaç gün içinde uygun adayları yönlendiriyoruz.' },
      { q: 'Yardımcı ve bakıcı arasındaki fark nedir?', a: 'Bakıcı bebek, çocuk, hasta veya yaşlı bakımına odaklanır; yardımcı ev işleri, temizlik ve genel destek sunar.' },
    ],
  },
  'pages/yatili-yardimci.html': {
    path: '/pages/yatili-yardimci.html',
    title: 'Yatılı Yardımcı Arıyorum | Yatılı Ev Yardımcısı — İstanbul',
    description: 'Yatılı yardımcı arıyorum — yatılı ev yardımcısı, yatılı bebek bakıcısı, yatılı çocuk bakıcısı. 7/24 evde konaklayan referanslı yatılı yardımcı temini. İstanbul.',
    keywords: 'yatılı yardımcı, yatılı yardımcı arıyorum, yatılı ev yardımcısı, yatılı ev yardımcısı arıyorum, yatılı bakıcı, yatılı bebek bakıcısı, istanbul yatılı yardımcı',
    service: 'Yatılı Yardımcı',
    faqs: [
      { q: 'Yatılı yardımcı ne yapar?', a: 'Evde konaklayarak bebek/çocuk bakımı, yaşlı bakımı, ev işleri, temizlik, yemek ve ütü hizmetleri sunar.' },
      { q: 'Yatılı yardımcı ile yatılı bakıcı farkı nedir?', a: 'Yatılı bakıcı öncelikle bakım odaklıdır; yatılı yardımcı bakımın yanı sıra ev işlerine de destek verebilir.' },
      { q: 'Yatılı yardımcı ücretleri ne kadar?', a: 'Deneyim ve hizmet türüne göre değişir. Ücretsiz teklif için formu doldurun.' },
    ],
  },
  'pages/gundelikci.html': {
    path: '/pages/gundelikci.html',
    title: 'Gündelikçi Arıyorum | Günlük Temizlik & Ev Temizliği — İstanbul',
    description: 'Gündelikçi arıyorum — ev temizliği, günlük temizlik, gündelik temizlik personeli. Güvenilir gündelikçi ve temizlik personeli temini. İstanbul geneli.',
    keywords: 'gündelikçi, gündelikçi arıyorum, günlük temizlik, gündelik temizlik, ev temizliği, temizlik personeli, ev temizliği için yardımcı, istanbul gündelikçi',
    service: 'Gündelikçi / Temizlik',
    faqs: [
      { q: 'Gündelikçi nedir?', a: 'Belirli günlerde veya tek seferlik olarak ev temizliği ve ev işlerine yardımcı olan temizlik personelidir.' },
      { q: 'Gündelikçi ile günlük temizlik personeli farkı nedir?', a: 'Gündelikçi genelde tek seferlik ihtiyaç içindir; günlük temizlik personeli düzenli tekrarlayan hizmettir.' },
      { q: 'Ev temizliği için gündelikçi bulabilir miyim?', a: 'Evet, ev temizliği, günlük temizlik ve gündelik temizlik için referanslı personel temin ediyoruz.' },
    ],
  },
  'pages/yabanci-bakici.html': {
    path: '/pages/yabanci-bakici.html',
    title: 'Yabancı Bakıcı Arıyorum | Referanslı Yabancı Uyruklu Bakıcı — İstanbul',
    description: 'Yabancı bakıcı arıyorum — Türkmen, Özbek, Filipinli çalışma izinli referanslı yabancı bakıcı. Yatılı yabancı bakıcı, gündüzlü yabancı bakıcı. İstanbul.',
    keywords: 'yabancı bakıcı, yabancı bakıcı arıyorum, yabancı uyruklu bakıcı, istanbul yabancı bakıcı, yatılı yabancı bakıcı, türkmen bakıcı, özbek bakıcı',
    service: 'Yabancı Uyruklu Bakıcı',
    faqs: [
      { q: 'Yabancı bakıcılar yasal mı çalışıyor?', a: 'Evet, tüm adaylarımız çalışma ve oturma izni süreçlerini tamamlamış kişilerdir.' },
      { q: 'Hangi uyruklardan yabancı bakıcı bulabilirim?', a: 'Türkmen, Özbek, Filipinli ve diğer uyruklardan referanslı bakıcı temin ediyoruz.' },
    ],
  },
  'pages/bebek-bakicisi.html': {
    path: '/pages/bebek-bakicisi.html',
    title: 'Bebek Bakıcısı Arıyorum | Yatılı & Gündüzlü Bebek Bakıcısı — İstanbul',
    description: 'Bebek bakıcısı arıyorum — referanslı bebek bakıcı temini. Yatılı bebek bakıcısı, gündüzlü bebek bakıcısı, yeni doğan bakıcısı. İstanbul geneli.',
    keywords: 'bebek bakıcısı, bebek bakıcısı arıyorum, yatılı bebek bakıcısı, gündüzlü bebek bakıcısı, referanslı bebek bakıcısı, istanbul bebek bakıcısı, yeni doğan bakıcısı',
    service: 'Bebek Bakıcısı',
    faqs: [
      { q: 'Bebek bakıcısı arıyorum, ne kadar sürede bulunur?', a: 'Genellikle birkaç gün içinde uygun adayları yönlendiriyoruz.' },
      { q: 'Yatılı bebek bakıcısı bulabilir miyim?', a: 'Evet, yatılı bebek bakıcısı ve gündüzlü bebek bakıcısı temin ediyoruz.' },
    ],
  },
  'pages/cocuk-bakicisi.html': {
    path: '/pages/cocuk-bakicisi.html',
    title: 'Çocuk Bakıcısı Arıyorum | Oyun Ablası & Dadı — İstanbul',
    description: 'Çocuk bakıcısı arıyorum — oyun ablası, dadı, okul sonrası bakıcı. Eğitimli referanslı çocuk bakıcısı temini. İstanbul geneli.',
    keywords: 'çocuk bakıcısı, çocuk bakıcısı arıyorum, oyun ablası arıyorum, dadı arıyorum, okul sonrası bakıcı, istanbul çocuk bakıcısı',
    service: 'Çocuk Bakıcısı',
  },
  'pages/ev-yardimcisi.html': {
    path: '/pages/ev-yardimcisi.html',
    title: 'Ev Yardımcısı Arıyorum | Ev İşlerine Yardımcı Kadın — İstanbul',
    description: 'Ev yardımcısı arıyorum — ev işlerine yardımcı kadın, yatılı ev yardımcısı, gündüzlü ev yardımcısı. Türkmen, Özbek ev yardımcısı. Temizlik ve yemek.',
    keywords: 'ev yardımcısı, ev yardımcısı arıyorum, ev işlerine yardımcı, ev işlerine yardımcı kadın arıyorum, yatılı ev yardımcısı, gündüzlü ev yardımcısı, istanbul ev yardımcısı',
    service: 'Ev Yardımcısı',
    faqs: [
      { q: 'Ev yardımcısı ne yapar?', a: 'Temizlik, yemek, ütü, alışveriş ve genel ev düzeni.' },
      { q: 'Yatılı ev yardımcısı bulabilir miyim?', a: 'Evet, yatılı ve gündüzlü ev yardımcısı temin ediyoruz.' },
    ],
  },
  'pages/ev-temizligi.html': {
    path: '/pages/ev-temizligi.html',
    title: 'Ev Temizliği | Günlük Temizlik & Gündelik Temizlik Personeli — İstanbul',
    description: 'Ev temizliği, günlük temizlik, gündelik temizlik hizmeti. Temizlik personeli, ev temizliği için yardımcı kadın. Gündelikçi seçenekleri. İstanbul.',
    keywords: 'ev temizliği, günlük temizlik, gündelik temizlik, temizlik personeli, ev temizliği için yardımcı, günlük temizlik personeli, gündelikçi, istanbul ev temizliği',
    service: 'Ev Temizliği',
    faqs: [
      { q: 'Günlük temizlik ile gündelik temizlik farkı nedir?', a: 'Günlük temizlik düzenli tekrarlayan hizmettir. Gündelik temizlik tek seferlik veya ihtiyaç anında alınan hizmettir.' },
      { q: 'Ev temizliği personeli ne yapar?', a: 'Genel ev temizliği, banyo, mutfak, toz alma, süpürme ve silme işlerini üstlenir.' },
    ],
  },
  'pages/yatili-bakici.html': {
    path: '/pages/yatili-bakici.html',
    title: 'Yatılı Bakıcı Arıyorum | 7/24 Yatılı Bakıcı & Yatılı Yardımcı — İstanbul',
    description: 'Yatılı bakıcı arıyorum — evde konaklayan 7/24 yatılı bakıcı, yatılı bebek bakıcısı, yatılı çocuk bakıcısı, yatılı yardımcı. Referanslı aday temini.',
    keywords: 'yatılı bakıcı, yatılı bakıcı arıyorum, yatılı yardımcı, yatılı bebek bakıcısı, yatılı ev yardımcısı, yatılı çocuk bakıcısı, istanbul yatılı bakıcı',
    service: 'Yatılı Bakıcı',
    faqs: [
      { q: 'Yatılı bakıcı ne yapar?', a: 'Evde konaklayarak gece dahil tam bakım, çocuk/yetişkin bakımı ve ev düzeni desteği sunar.' },
      { q: 'Yatılı bakıcı ile yatılı yardımcı farkı?', a: 'Yatılı bakıcı bakım odaklıdır; yatılı yardımcı bakıma ek ev işlerine de destek verebilir.' },
    ],
  },
  'pages/turkmen-bakici.html': {
    path: '/pages/turkmen-bakici.html',
    title: 'Türkmen Bakıcı Arıyorum | Referanslı Türkmen Bakıcı — İstanbul',
    description: 'Türkmen bakıcı arıyorum — referanslı, deneyimli Türkmen uyruklu bakıcı ve yardımcı. Yatılı Türkmen bakıcı, bebek bakımı, ev yardımcısı.',
    keywords: 'türkmen bakıcı, türkmen bakıcı arıyorum, yatılı türkmen bakıcı, referanslı türkmen bakıcı, istanbul türkmen bakıcı',
    service: 'Türkmen Bakıcı',
  },
  'pages/ozbek-bakici.html': {
    path: '/pages/ozbek-bakici.html',
    title: 'Özbek Bakıcı Arıyorum | Referanslı Özbek Bakıcı — İstanbul',
    description: 'Özbek bakıcı arıyorum — disiplinli, referanslı Özbek uyruklu bakıcı ve ev yardımcısı. Yatılı özbek bakıcı, bebek bakımı.',
    keywords: 'özbek bakıcı, özbek bakıcı arıyorum, yatılı özbek bakıcı, referanslı özbek bakıcı, istanbul özbek bakıcı',
    service: 'Özbek Bakıcı',
  },
  'pages/filipinli-bakici.html': {
    path: '/pages/filipinli-bakici.html',
    title: 'Filipinli Bakıcı Arıyorum | İngilizce Bilen Filipinli Bakıcı',
    description: 'Filipinli bakıcı arıyorum — çalışma izinli, İngilizce bilen profesyonel Filipinli bakıcı. Bebek ve çocuk bakımında deneyimli.',
    keywords: 'filipinli bakıcı, filipinli bakıcı arıyorum, ingilizce bilen bakıcı, yabancı bakıcı',
    service: 'Filipinli Bakıcı',
  },
  'pages/gunduzlu-bakici.html': {
    path: '/pages/gunduzlu-bakici.html',
    title: 'Gündüzlü Bakıcı Arıyorum | Part-time Bakıcı & Yardımcı',
    description: 'Gündüzlü bakıcı arıyorum — belirli saatlerde gelen gündüzlü bebek bakıcısı, okul sonrası bakıcı, gündüzlü yardımcı.',
    keywords: 'gündüzlü bakıcı, gündüzlü bakıcı arıyorum, part-time bakıcı, okul sonrası bakıcı, gündüzlü yardımcı',
    service: 'Gündüzlü Bakıcı',
  },
  'pages/yeni-dogan-bakici.html': {
    path: '/pages/yeni-dogan-bakici.html',
    title: 'Yeni Doğan Bakıcısı Arıyorum | 0-6 Ay Bebek Bakımı',
    description: 'Yeni doğan bakıcısı arıyorum — 0-6 ay bebek bakımında uzman, emzirme destekli yatılı yeni doğan bakıcı.',
    keywords: 'yeni doğan bakıcısı, yeni doğan bakıcı arıyorum, gece bakıcısı, emzirme destekli bakıcı',
    service: 'Yeni Doğan Bakıcısı',
  },
  'pages/hasta-bakicisi.html': {
    path: '/pages/hasta-bakicisi.html',
    title: 'Hasta Bakıcısı Arıyorum | Evde Hasta Bakımı — İstanbul',
    description: 'Hasta bakıcısı arıyorum — evde ve hastanede refakat, ameliyat sonrası bakım. Yatılı hasta bakıcı, Alzheimer bakıcısı.',
    keywords: 'hasta bakıcısı, hasta bakıcı arıyorum, evde hasta bakımı, yatılı hasta bakıcı, hastane refakatçisi',
    service: 'Hasta Bakıcısı',
  },
  'pages/yasli-bakicisi.html': {
    path: '/pages/yasli-bakicisi.html',
    title: 'Yaşlı Bakıcısı Arıyorum | Alzheimer & Demans Bakımı',
    description: 'Yaşlı bakıcısı arıyorum — Alzheimer, demans, Parkinson bakımında uzman. Yatılı yaşlı bakıcı, evde yaşlı bakımı.',
    keywords: 'yaşlı bakıcısı, yaşlı bakıcı arıyorum, alzheimer bakıcısı, yatılı yaşlı bakıcı, demans bakıcı',
    service: 'Yaşlı Bakıcısı',
  },
  'pages/refakatci.html': {
    path: '/pages/refakatci.html',
    title: 'Refakatçi Arıyorum | Hastane ve Evde Refakat',
    description: 'Refakatçi arıyorum — hastane refakatçisi, evde refakat, ameliyat sonrası refakat hizmeti.',
    keywords: 'refakatçi, refakatçi arıyorum, hastane refakatçisi, yatılı refakatçi',
    service: 'Refakatçi',
  },
  'pages/ingilizce-bilen-bakici.html': {
    path: '/pages/ingilizce-bilen-bakici.html',
    title: 'İngilizce Bilen Bakıcı Arıyorum | Filipinli Bakıcı',
    description: 'İngilizce bilen bakıcı arıyorum — Filipinli, yabancı uyruklu İngilizce konuşan bakıcı ve yardımcı temini.',
    keywords: 'ingilizce bilen bakıcı, filipinli bakıcı, yabancı bakıcı, ingilizce eğitimli bakıcı',
    service: 'İngilizce Bilen Bakıcı',
  },
  'pages/hakkimizda.html': {
    path: '/pages/hakkimizda.html',
    title: 'Hakkımızda | Benim Bakıcım — Bakıcı & Yardımcı Danışmanlığı',
    description: 'Benim Bakıcım — 8 yıllık deneyimle bakıcı, yardımcı, ev temizliği ve gündelikçi temini. İstanbul genelinde bakıcı danışmanlığı.',
    keywords: 'benim bakıcım, bakıcı danışmanlığı, bakıcı ajansı istanbul, yardımcı danışmanlık',
  },
  'pages/iletisim.html': {
    path: '/pages/iletisim.html',
    title: 'İletişim | Bakıcı & Yardımcı Talebi — Benim Bakıcım',
    description: 'Bakıcı veya yardımcı talebi için iletişime geçin. WhatsApp 0535 596 35 45. İstanbul geneli — ücretsiz danışmanlık.',
    keywords: 'bakıcı iletişim, yardımcı talep, bakıcı danışmanlık istanbul, benimbakicim iletişim',
  },
  'pages/ilan-ver.html': {
    path: '/pages/ilan-ver.html',
    title: 'Bakıcı İlan Ver | Standart 1.000 TL · Acil 1.500 TL — Benim Bakıcım',
    description: 'Standart 1.000 TL, Acil 1.500 TL. WhatsApp katalogdan sipariş, havale/EFT ile ödeme (açıklamaya ilan kodu); onay sonrası ilan. Paket başına en fazla 3 başvuru.',
    keywords: 'bakıcı ilan ver, standart ilan paketi, acil ilan paketi, havale eft, bakıcı havuzu',
  },
  'pages/is-ilanlari.html': {
    path: '/pages/is-ilanlari.html',
    title: 'Bakıcı & Yardımcı İş İlanları | Bakıcı Olarak İş Ara',
    description: 'Bakıcı, yardımcı, gündelikçi ve temizlik personeli iş ilanları. 4904 sayılı Kanun uyarınca iş arayanlardan ücret alınmaz.',
    keywords: 'bakıcı iş ilanları, yardımcı iş ilanları, temizlik iş ilanları, bakıcı iş arıyorum',
  },
  'pages/sss.html': {
    path: '/pages/sss.html',
    title: 'SSS | Bakıcı, Yardımcı ve Ev Temizliği Rehberi',
    description: 'Bakıcı arıyorum, yatılı yardımcı, gündelikçi, bebek bakıcısı, ücretler ve referans kontrolü hakkında sık sorulan sorular.',
    keywords: 'bakıcı sss, bakıcı nasıl bulunur, yatılı yardımcı ücretleri, gündelikçi fiyatları, bakıcı arıyorum rehberi',
    faqs: [
      { q: 'Bakıcı arıyorum, süreç nasıl işliyor?', a: 'Formu doldurun, danışmanımız 24-48 saat içinde sizi arayarak ihtiyacınızı dinler ve adayları sunar.' },
      { q: 'Yatılı yardımcı bulabilir miyim?', a: 'Evet, yatılı yardımcı, yatılı bakıcı ve yatılı ev yardımcısı temin ediyoruz.' },
      { q: 'Gündelikçi hizmeti var mı?', a: 'Evet, gündelikçi, günlük temizlik ve ev temizliği personeli temin ediyoruz.' },
      { q: 'Referans kontrolü yapılıyor mu?', a: 'Evet, tüm adayların referansları aranır, sabıka kaydı sorgulanır.' },
      { q: 'Bakıcı ücretleri ne kadar?', a: 'Deneyim, çalışma şekli ve hizmet türüne göre değişir. Ücretsiz teklif için iletişime geçin.' },
    ],
  },
  'pages/referanslarimiz.html': {
    path: '/pages/referanslarimiz.html',
    title: 'Referanslarımız | Mutlu Aile Yorumları',
    description: 'Benim Bakıcım müşteri yorumları — bebek bakıcısı, yardımcı ve ev temizliği hizmetlerinden memnun aileler.',
    keywords: 'bakıcı referansları, yardımcı yorumları, benim bakıcım referans',
  },
  'pages/bakici-secim-sureci.html': {
    path: '/pages/bakici-secim-sureci.html',
    title: 'Bakıcı Seçim Süreci | Güvenilir Bakıcı Nasıl Bulunur?',
    description: 'Bakıcı ve yardımcı seçim sürecimiz: mülakat, referans kontrolü, sabıka kaydı doğrulaması.',
    keywords: 'bakıcı seçim süreci, güvenilir bakıcı nasıl bulunur, referans kontrolü',
  },
  'pages/kvkk.html': {
    path: '/pages/kvkk.html',
    title: 'KVKK Aydınlatma Metni | Benim Bakıcım',
    description: 'Benim Bakıcım KVKK aydınlatma metni: kişisel verilerin işlenme amacı, hukuki sebep ve haklarınız.',
    keywords: 'kvkk, kişisel verilerin korunması',
  },
  'pages/gizlilik.html': {
    path: '/pages/gizlilik.html',
    title: 'Gizlilik Politikası | Benim Bakıcım',
    description: 'Benim Bakıcım gizlilik politikası: toplanan veriler, kullanım amaçları ve saklama.',
    keywords: 'gizlilik politikası',
  },
  'pages/kullanim-kosullari.html': {
    path: '/pages/kullanim-kosullari.html',
    title: 'Kullanım Koşulları | Benim Bakıcım',
    description: 'Benim Bakıcım web sitesi kullanım koşulları ve dijital ilan hizmeti kuralları.',
    keywords: 'kullanım koşulları',
  },
  'pages/cerez-politikasi.html': {
    path: '/pages/cerez-politikasi.html',
    title: 'Çerez Politikası | Benim Bakıcım',
    description: 'Benim Bakıcım çerez politikası.',
    keywords: 'çerez politikası',
  },
  'pages/mesafeli-satis-sozlesmesi.html': {
    path: '/pages/mesafeli-satis-sozlesmesi.html',
    title: 'Mesafeli Satış Sözleşmesi | Benim Bakıcım',
    description: 'Dijital ilan yayını ve başvuru iletim hizmeti için mesafeli satış sözleşmesi, fiyat ve teslimat şartları.',
    keywords: 'mesafeli satış sözleşmesi, ilan paketi',
  },
  'pages/iptal-iade.html': {
    path: '/pages/iptal-iade.html',
    title: 'İptal ve İade Koşulları | Benim Bakıcım',
    description: 'İlan paketi iptal, cayma hakkı ve iade koşulları.',
    keywords: 'iptal iade, cayma hakkı',
  },
  'pages/tesekkur.html': {
    path: '/pages/tesekkur.html',
    title: 'Talebiniz Alındı | Benim Bakıcım',
    description: 'Form talebiniz alındı. WhatsApp üzerinden dönüş yapılacaktır.',
    keywords: '',
    noindex: true,
  },
};

module.exports = { SITE_URL, SITE_NAME, DEFAULT_OG_IMAGE, GLOBAL_KEYWORDS, BUSINESS, PAGE_SEO };
