name = "benimbakicim"
compatibility_date = "2025-10-01"
main = "./dist/_worker.js"
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
PUBLIC_SITE_URL = "https://benimbakicim.com"

[[routes]]
pattern = "benimbakicim.com/*"
zone_name = "benimbakicim.com"

[[routes]]
pattern = "www.benimbakicim.com/*"
zone_name = "benimbakicim.com"
